org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_license=GNU GPL 3.0
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.78
neo_version_range=[26.1.2,)
loader_version_range=[3,)
minecraft_version=26.1.2
mod_authors=Flechazo, MerrySnow, zhenshiz, _yi_ran_
mod_description=Mafuyu never like you.
# OneEnoughItem (oei)
oei_mod_id=oneenoughitem
oei_mod_name=OneEnoughItem
oei_mod_group_id=cc.sighs
oei_mod_version=1.0.0
oei_mod_authors=Flechazo, MerrySnow, zhenshiz, _yi_ran_
oei_mod_description=为物品提供可配置的替换规则与编辑界面。
oei_oelib_version_range=[0.0.1,)
# OneEnoughBlock (oeb)
oeb_mod_id=oneenoughblock
oeb_mod_name=OneEnoughBlock
oeb_mod_group_id=cc.sighs
oeb_mod_version=1.0.0
oeb_mod_authors=MerrySnow, _yi_ran_
oeb_mod_description=为方块提供可配置的替换规则与编辑界面。
# OneEnoughFluid (oef)
oef_mod_id=oneenoughfluid
oef_mod_name=OneEnoughFluid
oef_mod_group_id=cc.sighs
oef_mod_version=1.0.0
oef_mod_authors=Flechazo, _yi_ran_
oef_mod_description=为流体提供可配置的替换规则与编辑界面。
