org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
mod_license=GNU GPL 3.0
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.78
neo_version_range=[26.1.2,)
loader_version_range=[3,)
minecraft_version=26.1.2
mod_authors=Flechazo, MerrySnow, zhenshiz, _yi_ran_
mod_description=Mafuyu never like you.
# OneEnoughItem (oei)
oei_mod_id=oneenoughitem
oei_mod_name=OneEnoughItem
oei_mod_group_id=com.mafuyu404
oei_mod_version=1.0.8
oei_mod_authors=Mafuyu404
oei_mod_description=Mafuyu never like you.
oei_oelib_version_range=[0.0.1,)
# OneEnoughBlock (oeb)
oeb_mod_id=oneenoughblock
oeb_mod_name=OneEnoughBlock
oeb_mod_group_id=com.sighs
oeb_mod_version=1.1.2-hotfix
oeb_mod_authors=Mafuyu404
oeb_mod_description=Mafuyu never like you.
# OneEnoughFluid (oef)
oef_mod_id=oneenoughfluid
oef_mod_name=OneEnoughFluid
oef_mod_group_id=com.flechazo
oef_mod_version=1.1.1-hotfix
oef_mod_authors=
oef_mod_description=
