modLoader = "javafml"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license = "GPL-3.0 license"

[[mods]]
modId = "oneenoughitem"
version = "1.0.8"
displayName = "oneenoughitem"
authors = "Flechazo, SnowMerry, zhenshiz, _yi_ran_"
description = "Mafuyu never like you."
logoFile = "assets/oneenoughitem/web/img/img.png" #optional

[[dependencies.oneenoughitem]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oneenoughitem]]
modId = "oelib"
type = "required"
versionRange = "[0.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oneenoughitem]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "oneenoughitem.mixins.json"
